version: '3.7'

services:
  dd:
    image: gcr.io/datadoghq/agent:latest
    container_name: dd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - /proc/:/host/proc/:ro 
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro 
    ports:
      - 8126:8126/tcp 
      - 8125:8125/udp
    environment:
      - DD_LOGS_ENABLED='true'
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL="true"
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC="true"
      - DD_APM_ENABLED="true"
      - DD_HOSTNAME="MyLocalComputer"
      - DD_ENV="testeLocal"
      - NON_LOCAL_TRAFFIC="false"
      - DD_API_KEY=""

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
  
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "29092:29092"
    links:
     - zookeeper
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092 #, PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  redis:
    image: redis
    ports:
      - "6379:6379"