version: "3.7"
services:     
  mongodb_sap:
    container_name: mongodb_senna1
    image: mongo:4.2.5-bionic
    ports:
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: senna_user
      MONGO_INITDB_ROOT_PASSWORD: senna_password
      MONGO_INITDB_DATABASE: senna_db