version: '3'

services:
  mysql:
    image: mysql
#     image: mysql:5.7
    container_name: mysql
    ports:
      - "3307:3306"
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: mysqlDB
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123456789