version: '3'

services:
  myslqdb:
    image: mysql:5.7
    container_name: myslqdb
    ports:
      - "3306:3306"
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: "123456789"
      MYSQL_DATABASE: myslqdb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123456789  